version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: container_mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cepdb
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"